services:
  mc_heavy:
    image: glitchless/gli_mc_vanilla:1
    ports:
      - "25566:25565"
    environment:
      MC_RAM: "12G"
    volumes:
      - ./world:/app/world
      - ./world_nether:/app/world_nether
      - ./world_the_end:/app/world_the_end
      - ./logs:/app/logs
      - ./plugins:/app/plugins
